### ISSUE TITLE
Extra vector<bool> test cases

### ISSUE THREAD

**Issue by ecorm** [ecorm/cppwamp#58]
4cb507b1ac1d40dcb99e7a983fda456803971f85 added test cases for Variant comparisons involving `vector<bool>`. There should probably be more of these test cases for other operations, such as construction, assignment, and conversion.

**Comment by taion** [comment]
It looks like `checkVec` already covers assignment and conversion, and it's used on `vector<bool>`. Is this just a matter of adding a check for construction from a `vector<T>` there?

**Comment by ecorm** [comment]
I haven't looked into it yet. This issue was intended as a reminder for me (or anyone else) to look into what's covered now, and what's missing with regards to `vector<bool>`.

**Comment by taion** [comment]
Got it. The current test coverage is pretty good; it was just the comparison cases that were missing. Making clang work was just a matter of getting the tests to build and pass.

When you do want to take a look, for reference -

You run `checkVec` on both non-empty (https://github.com/ecorm/cppwamp/blob/4ae75965e9cb8090253b951be91ce3a79b3c05ec/test/varianttestvector.cpp#L130-L132) and empty (https://github.com/ecorm/cppwamp/blob/4ae75965e9cb8090253b951be91ce3a79b3c05ec/test/varianttestvector.cpp#L156) bool arrays.

In `checkVec`, you check copy assignment (https://github.com/ecorm/cppwamp/blob/4ae75965e9cb8090253b951be91ce3a79b3c05ec/test/varianttestvector.cpp#L30-L32), move assignment (https://github.com/ecorm/cppwamp/blob/4ae75965e9cb8090253b951be91ce3a79b3c05ec/test/varianttestvector.cpp#L54-L56), and conversion (https://github.com/ecorm/cppwamp/blob/4ae75965e9cb8090253b951be91ce3a79b3c05ec/test/varianttestvector.cpp#L38-L49).

You exercise construction from a `vector` in both `same` and `differs`. It looks like this case isn't explicitly checked in `checkVec`, though. #59 adds that, but it's really trivial.

**Comment by ecorm** [comment]
With #59, it looks like all bases are covered. Thanks for looking into this!
