### ISSUE TITLE
Should the variant facilities be its own library?

### ISSUE THREAD

**Issue by ecorm** [ecorm/cppwamp#71]
I'm wondering if the `Variant` facilities of CppWAMP should be part of their own library. This sub-library could be useful for folks that need to represent JSON objects in C++, even if they're not using WAMP.

**Comment by taion** [comment]
I can't immediately think of a use case on my end, but it does seem like the `Variant`s are really cool and pretty non-trivial, and I could see myself using them in non-CppWAMP contexts down the road.

**Comment by ecorm** [comment]
Variant shall remain within CppWAMP. I have a closed-source serialization library in the works that includes a replacement for Variant. If my employer allows me to open-source this serialization library, it shall be adopted by CppWAMP and would eliminate the dependencies on other serialization libraries.
