### ISSUE TITLE
Provide connection/session failure callback.

### ISSUE THREAD

**Issue by ecorm** [ecorm/cppwamp#78]
Consider providing a way to notify one or more observers when a connection is dropped or when the session is closed by the other peer.

**Comment by michaelaeriksen** [comment]
I have issues with dropped connections and currently the only way to fix is a restart of program at the moment. Any pointers of how to fix this?

**Comment by ecorm** [comment]
Sorry, I haven't yet put any thought in how I'd implement this. It's not an urgent feature for my project because Crossbar is hosted on the same device as my C++ program.
