### ISSUE TITLE
Improve scoped registration example

### ISSUE THREAD

**Issue by estan** [ecorm/cppwamp#87]
I was looking at the scoped registration example in the tutorial (and reference docs):

``` cpp
struct Delegate
{
    Outcome rpc(Invocation inv);

    ScopedRegistration reg;
}

int main()
{
    boost::asio::io_service iosvc;
    boost::asio::spawn(iosvc, [&](boost::asio::yield_context yield)
    {
        auto session = CoroSession<>::create(connectorList);
        session->connect(yield);
        session->join("somerealm", yield);

        {
            using std::placeholders;
            Delegate delegate;
            delegate.reg = session->enroll(
                            Procedure("someprocedure"),
                            std::bind(&Delegate::rpc, delegate, _1),
                            yield);

        }  // When the 'delegate' object leaves this scope, its
           // ScopedRegisration member gets destroyed. This will
           // automatically unregister the regisration, thereby avoiding
           // further member function calls on the deleted 'delegate'
           // object.
    });
    iosvc.run();
}
```

Correct me if I'm wrong, but will this not register the slot and then almost immediately unregister it when the scope is exited? If so, could the example be made more realistic without complicating it too much? If not, please set me straight on what happens :)

**Comment by ecorm** [comment]
> Correct me if I'm wrong, but will this not register the slot and then almost immediately unregister it when the scope is exited?

Yes, that's what it does. I should have added some operations between the registration and a `ScopedRegistration` going out of scope.

I have a more realistic example in mind, based on how I'm actually using CppWAMP in real life. I'll update the example when I get the chance.

**Comment by estan** [comment]
:+1:
